warehouse: #profile name
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ikb44942.us-east-1

      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: accountadmin
      database: movie_rental
      warehouse: compute_wh
      schema: raw
      threads: 12
      client_session_keep_alive: False
    
    prod:
      type: snowflake
      account: ikb44942.us-east-1

      user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
      password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'

      role: accountadmin
      database: movie_rental
      warehouse: compute_wh
      schema: raw
      threads: 12
      client_session_keep_alive: False