version: 2

models:
  - name: actor
    columns:
      - name: actor_id
        tests:
          - not_null
          - unique
  - name: film_actor
    columns:
      - name: film_actor_key
        tests: 
          - not_null
          - unique