version: 2

sources:
  - name: movie_rental
    database: movie_rental
    schema: raw
    tables:
      - name: actor
      - name: actor_info
      - name: address
      - name: category
      - name: city
      - name: country
      - name: customer
      - name: customer_list
      - name: film
      - name: film_actor
      - name: film_category
      - name: film_list
      - name: inventory
      - name: language
      - name: nicer_but_slower_film_list
      - name: payment
      - name: rental
      - name: sales_by_film_category
      - name: sales_by_store
      - name: staff
      - name: staff_list
      - name: store